# Generated by Django 4.1.8 on 2023-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de validation des CGUs"),
        ),
    ]
