# Generated by Django 4.1.8 on 2023-05-03 13:45

import django.contrib.postgres.fields.citext
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userapplicationlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "email",
                    django.contrib.postgres.fields.citext.CIEmailField(
                        max_length=254, primary_key=True, serialize=False, verbose_name="adresse e-mail"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="date de création"
                    ),
                ),
                ("verified_at", models.DateTimeField(null=True, blank=True, verbose_name="date de vérification")),
            ],
            options={
                "verbose_name": "addresse e-mail",
                "verbose_name_plural": "addresses e-mail",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                blank=True, db_index=True, max_length=254, verbose_name="adresse e-mail"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                models.F("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="unique_email_if_not_empty",
                violation_error_message="Cet email est déjà associé à un autre utilisateur.",
            ),
        ),
        migrations.AddField(
            model_name="emailaddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
