# Generated by Django 4.1.9 on 2023-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_emailaddress_verification"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emailaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("verified_at", None), _negated=True),
                fields=("user",),
                name="unique_email_verified_per_user",
                violation_error_message="Un utilisateur ne peut pas avoir plusieurs e-mails vérifiés.",
            ),
        ),
    ]
