# Generated by Django 4.1.9 on 2023-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_emailaddress_unique_email_not_verified_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_reset_password",
            field=models.BooleanField(default=False, verbose_name="mot de passe temporaire"),
        ),
    ]
