# Generated by Django 4.1.9 on 2023-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_must_reset_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="next_redirect_uri",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="next_redirect_uri_stored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
