# Generated by Django 4.1.9 on 2023-06-23 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("users", "0008_user_next_redirect_uri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="support_for",
            field=models.ManyToManyField(related_name="support_for", to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
