# Generated by Django 4.2.4 on 2023-09-08 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("users", "0009_alter_emailaddress_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userapplicationlink",
            unique_together={("user", "application")},
        ),
    ]
