# Generated by Django 4.2.6 on 2023-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_federation_user_federation_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="federation_id_token_hint",
            field=models.TextField(null=True, verbose_name="IdToken"),
        ),
    ]
