# Generated by Django 4.2.7 on 2023-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_federation_id_token_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_email_already_used",
            field=models.TextField(null=True),
        ),
    ]
