# Generated by Django 4.2.7 on 2023-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_new_email_already_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_is_too_weak",
            field=models.BooleanField(default=False, verbose_name="mot de passe trop faible"),
        ),
    ]
