# Generated by Django 5.1.5 on 2026-04-28 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_unique_sub_per_federation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_sub_per_federation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="federation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="federation_data",
        ),
        migrations.RemoveField(
            model_name="user",
            name="federation_id_token_hint",
        ),
        migrations.RemoveField(
            model_name="user",
            name="federation_sub",
        ),
        migrations.RemoveField(
            model_name="user",
            name="new_email_already_used",
        ),
    ]
