# Generated by Django 4.1.8 on 2023-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JWTHashSecret",
            fields=[
                ("realm_id", models.TextField(primary_key=True, serialize=False)),
                ("secret", models.TextField()),
            ],
        ),
    ]
