# Generated by Django 4.2.7 on 2023-11-16 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("keycloak_compat", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JWTHashSecret",
        ),
    ]
