# Generated by Django 6.0.6 on 2026-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SamlServiceProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Libellé interne du service provider.",
                        max_length=255,
                        verbose_name="nom",
                    ),
                ),
                ("entity_id", models.CharField(editable=False, max_length=255, unique=True, verbose_name="entityID")),
                (
                    "metadata",
                    models.TextField(
                        help_text="Coller les métadonnées SAML du service provider. "
                        "L'entityID et les URLs ACS en sont extraits.",
                        verbose_name="métadonnées XML",
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sous-ensemble d'attributs publiés et, par attribut, le nom et le NameFormat émis. "
                        "Vide = mapping par défaut de l'IdP.",
                        verbose_name="mapping d'attributs",
                    ),
                ),
                (
                    "nameid_format",
                    models.CharField(
                        choices=[
                            (
                                "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                                "persistent (UUID, identique au sub OIDC)",
                            ),
                            ("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "emailAddress"),
                        ],
                        default="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
                        max_length=256,
                        verbose_name="format du NameID",
                    ),
                ),
                ("sign_assertion", models.BooleanField(default=True, verbose_name="signer l'assertion")),
                (
                    "encrypt_assertion",
                    models.BooleanField(
                        default=False,
                        help_text="N'a d'effet que si les métadonnées du SP publient un certificat de chiffrement.",
                        verbose_name="chiffrer l'assertion",
                    ),
                ),
                (
                    "require_signed_authn_request",
                    models.BooleanField(
                        default=False,
                        help_text="Rejeter les AuthnRequest non signées de ce SP. "
                        "À activer une fois le SP capable de signer.",
                        verbose_name="exiger des AuthnRequest signées",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
            ],
            options={
                "verbose_name": "service provider SAML",
                "verbose_name_plural": "services providers SAML",
            },
        ),
    ]
