# Generated by Django 4.2.13 on 2024-06-27 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stats",
            unique_together={("user", "application", "date", "action")},
        ),
    ]
