# Generated by Django 4.1.9 on 2023-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_overrides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(blank=True, help_text="Allowed Post Logout URIs list, space separated"),
        ),
    ]
