# Generated by Django 5.1.15 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_overrides", "0003_application_allowed_origins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
            ),
        ),
    ]
