# Generated by Django 6.0.8 on 2026-09-08 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oidc_overrides", "0004_alter_application_authorization_grant_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="hash_client_secret",
        ),
    ]
