name: 🔮 CI

on:
  push:
    branches-ignore:
      - master_clever  # rename once we chose branch names

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    env:
      DJANGO_SETTINGS_MODULE: inclusion_connect.settings.test
      PYTHONPATH: .
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: 🐘 Non-durable PostgreSQL
      run: |
        psql <<SQL
          ALTER SYSTEM SET fsync=off;
          ALTER SYSTEM SET synchronous_commit=off;
          ALTER SYSTEM SET full_page_writes=off;
        SQL
        docker kill --signal=SIGHUP ${{ job.services.postgres.id }}
      env:
        PGPASSWORD: password
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: 5433
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: 💾 Create a database to check migrations
      run: createdb inclusion_connect
      env:
        PGPASSWORD: password
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: 5433
    - name: ⛨ Generate test SSH private key
      run: openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out oidc.pem
    - name: 💂 Install Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"
        cache: pip
        cache-dependency-path: requirements/dev.txt
    - name: 📥 Install dependencies
      run: make venv
    - name: ✨ ruff & djlint
      run: make quality
    - name: 🤹 Django tests
      run: make test

  dependabot:
    needs: [build] # only merge if build is green
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'gip-inclusion/inclusion-connect' }}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98  # v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: |
          gh pr review --approve "$PR_URL"
          gh pr merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
